---
title: "OCSALS 2023: Oral Presentation 3 Feedback"
date: '2023-08-25'
output: 
  word_document: 
    reference_docx: "/Users/danielparsons/dparsonsiuj@gmail.com - Google Drive/My Drive/01_Research/Testing/assets/OCSALS_style.docx"
params:
  personal.details.flex: ""
  intro.advice.flex: ""
  detailed.advice.flex: ""
  impressive.points.flex: ""
  both.scores: ""
  time.info: ""
  total.score: ""
  penalty.comment: ""
  key.word: ""
---

```{r setup, include=FALSE, ft.split = TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dpi = 300)
library(officer)
library(knitr)

```
`r personal.details.flex`
## Feedback
`r key.word`
<br>
`r intro.advice.flex`
<br>
`r detailed.advice.flex`
<br>
`r impressive.points.flex`
\newpage

## Scoring Details

```{r figure1, echo = FALSE, figure.align = "center", fig.width=6, fig.height = 4, out.width="4.5in", fig.cap="Your score compared with the average score in the IEP for Oral Presentation 2"}

par(mar = c(0,0,0,0))
radarchart(
    both.scores,
    axistype = 1,
    pcol = c(NA, 2), pfcol = scales::alpha(c("#99999980", NA), 0.5), plwd = 2, plty = 1,
    cglcol = "grey", cglty = 1, cglwd = 0.8,
    axislabcol = "navy",
    vlcex = 1.3, vlabels = colnames(both.scores),
    caxislabels = c("1", "2", "3", "4", "5")
  )

your.score = both.scores[c(3,4),]
kable(your.score, digits = 1)

kable(total.score, digits = 2)

```
`r time.info`
<br>
`r penalty.comment`
The total score is out of 100. See the rubric for calculation details.
<br>

<br>







